### PR TITLE
Support basic array values

### PR DESCRIPTION
**Pull request by janlazo**
I need to display multiple values in one table cell via an array but all contents in that table cell must be searchable via the search directive. `String(arr)` is a comma-delimited string so searching a single comma matches all table cells with multiple values.

### CODE REVIEW

**Comment by janlazo** [comment]
cc @lorenzofox3

**Comment by lorenzofox3** [comment]
can you try to run a benchmark with and without your changes. I am worried that creating an array on each searchable cell will introduce some overhead

**Comment by janlazo** [comment]
Running the example code with a 10000+ entries in the array gives me +20ms increase in the worst case. Tested on node v10.17.0 running on Ubuntu Xenial.

**Comment by lorenzofox3** [comment]
There is something I don't understand: even before your modification the text search on array seems to work fine:

```javascript
  const collection = [
        {a: 'Woo', b: ['foo', 'bar', 'bim']},
        {a: 'Woo', b: ['fob', 'baz', 'cim']},
        {a: 'Woo', b: ['for', 'woo', 'bam']}
    ];
    const ouptut = search({value: 'im', scope: ['a', 'b']})(collection);

// output > will match bim and cim
```

**Comment by janlazo** [comment]
`String(array)` creates comma delimited strings which is problematic for arrays that have string values with commas. My use-case is displaying multiple phrases/sentences in a list within a table cell. It must be in a table cell (no UI redesign allowed) and each phrase may contain commas. Without this patch, a single comma will match all rows with an array value with 2+ entries.

**Comment by lorenzofox3** [comment]
Ok, I see. That's a bit of an edge case. I don't really assume people to fill search fields with coma tokens (in other full text search engine like Elastic Search or Postgres, etc they are usually ignored)

The whole thing of [Inversion of Control](https://en.wikipedia.org/wiki/Inversion_of_control) is to let the user handle its edge cases while providing a robust and simple generic implementation for the 90%. Don't get me wrong, your PR is fine but I don't want such edge cases to make it into the code base. In your case you should probably wrap the default search factory with your custom code whenever it finds an array and then pass this custom search factory to the table. That would be more inline with the idea of inversion of control.

thanks, cheers

**Pull request closed without merging**
